### ISSUE TITLE
Is it slow?

### ISSUE THREAD

**Issue by Dirk23** [Mapotempo/osrm-isochrone-server#1]
Hi,

i was searching for exactly such a tool, wich we can use to calculate isochrones. I installed it and it seems to work fine. The only thing we are wondering about is, that the time for every request to the server and the result takes around 4-5 seconds, doesnt matter how high we set the time variable.
Our Server has 6 Cores and 64GB RAM, and i really cant see much CPU or RAM usage while a request. I can see that the process node takes up to 100% CPU, wich means it only runs on one core, right?

How can we speed your Serversoftware?

**Comment by frodrigo** [comment]
Hi. We already made lot of speed improvement on this piece of software. Yes it's run on one thread only.

Nevertheless I can now advice you to use the branch with native computation
https://github.com/Project-OSRM/osrm-backend/tree/ch_isochrone_poc
